"""Semantic names for MHR facial expression coefficients."""


# Position ``i`` names ``face_expr_coeffs[:, i]`` in MHR v1.x assets.
FACE_EXPRESSION_NAMES: tuple[str, ...] = (
    "browLowerer_L",
    "browLowerer_R",
    "cheekPuff_L",
    "cheekPuff_R",
    "cheekRaiser_L",
    "cheekRaiser_R",
    "cheekSuck_L",
    "cheekSuck_R",
    "chinRaiser_B",
    "chinRaiser_T",
    "dimpler_L",
    "dimpler_R",
    "eyesClosed_L",
    "eyesClosed_R",
    "eyesLookDown_L",
    "eyesLookDown_R",
    "eyesLookLeft_L",
    "eyesLookLeft_R",
    "eyesLookRight_L",
    "eyesLookRight_R",
    "eyesLookUp_L",
    "eyesLookUp_R",
    "innerBrowRaiser_L",
    "innerBrowRaiser_R",
    "jawDrop",
    "jawSidewaysLeft",
    "jawSidewaysRight",
    "jawThrust",
    "lidTightener_L",
    "lidTightener_R",
    "lipCornerDepressor_L",
    "lipCornerDepressor_R",
    "lipCornerPuller_L",
    "lipCornerPuller_R",
    "lipFunneler_LB",
    "lipFunneler_LT",
    "lipFunneler_RB",
    "lipFunneler_RT",
    "lipPressor_L",
    "lipPressor_R",
    "lipPucker_L",
    "lipPucker_R",
    "lipStretcher_L",
    "lipStretcher_R",
    "lipSuck_LB",
    "lipSuck_LT",
    "lipSuck_RB",
    "lipSuck_RT",
    "lipTightener_L",
    "lipTightener_R",
    "lipsToward_LB",
    "lipsToward_LT",
    "lipsToward_RB",
    "lipsToward_RT",
    "lowerLipDepressor_L",
    "lowerLipDepressor_R",
    "mouthLeft",
    "mouthRight",
    "nasolabialFurrow_L",
    "nasolabialFurrow_R",
    "noseWrinkler_L",
    "noseWrinkler_R",
    "nostrilCompressor_L",
    "nostrilCompressor_R",
    "nostrilDilator_L",
    "nostrilDilator_R",
    "outerBrowRaiser_L",
    "outerBrowRaiser_R",
    "upperLidRaiser_L",
    "upperLidRaiser_R",
    "upperLipRaiser_L",
    "upperLipRaiser_R",
)


__all__ = ["FACE_EXPRESSION_NAMES"]
